language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - TESTBENCH_VERSION=3.2.*

before_script:
  - travis_retry composer self-update
  - travis_retry composer require --prefer-source --no-interaction --dev "orchestra/testbench:${TESTBENCH_VERSION}"

script:
  - composer validate
  - vendor/bin/phpunit
